server:
  port: 0
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
